name: Convert Excel to CSV
permissions: write-all
#on:
#  schedule:
#    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py

      - name: Convert Excel to CSV
        run: |
          python convert.py
          
      - name: Push files
        run: |
          git config --global user.email "srilanka@aiesec.net"
          git config --global user.name "aslgithubbot"
          git add .
          git commit -m "CSV Update"
          git push
